services:
  tech-challenge-api:
    build:
      dockerfile: ./api/Dockerfile
      context: ./
    ports:
      - "8888:8888"
    volumes:
      - ./api:/app
    environment:
      - PYTHONPATH=/app

  tech-challenge-web:
    build:
      dockerfile: ./web/Dockerfile
      context: ./
    ports:
      - "8501:8501"
    volumes:
      - ./web:/app
    environment:
      - API_URL=http://tech-challenge-api:8888
    depends_on:
      - tech-challenge-api
